### ISSUE TITLE
[sunu] Downloadlinks on Project settings not working

### ISSUE THREAD

**Issue by y0va** [OpenOlitor/openolitor-client-admin#305]
Nothing happens if I click on the 'Download' links next to 'Style' on https://sunuwwwtest.applicationcloud.io/admin/#/projektsettings. Only 'Importdatei' is working.

**Comment by AlwinEgger** [comment]
Starting a project, no customized CSS File is available and therefore no download is possible. After uploading a file for the first time, the download works fine.
I did this for sunuwwwtest.

It might be good to add an information about this behavior and/or not show the download-link, if there is no file yet. I added this to the wish-list.
