### ISSUE TITLE
E-Mail-Versand falsche Anzahl an Personen

### ISSUE THREAD

**Issue by budda85** [OpenOlitor/openolitor-client-admin#460]
Die Weboberfläche merkt sich anscheinend welche Mitglieder angewählt wurden.

![2020-05-25_21-13-19](https://user-images.githubusercontent.com/20152200/82838504-c2fb7d80-9ecc-11ea-905f-4a1f4322560c.png)

Zuvor waren 6 Mitglieder angewählt und davon wurden 5 wieder abgewählt.
Es ist also nur noch ein Mitglied angewählt aber es sollen sechs Mails verschickt werden.

**Comment by AlwinEgger** [comment]
Das Problem kann ich bestätigen. Sobald der Wizard geöffnet wird, werden die Änderungen in der Auswahl nicht mehr übernommen. Dies müsste aber so sein.

Wir haben ein Issue im internen System erstellt und werden informieren, sobald das Problem behoben wurde.

**Comment by mcmpp** [comment]
Hi @budda85 

This issue was solved. It will be merge soon but in mean time you could test it in try.openolitor.ch

Thanks for the feedback

**Comment by AlwinEgger** [comment]
Now merged and deployed 

https://github.com/OpenOlitor/openolitor-client-admin/releases/tag/2.4.2
