### ISSUE TITLE
Remove visible check message while creating invoices

### ISSUE THREAD

**Issue by mcmpp** [OpenOlitor/openolitor-client-admin#464]
In order to recreate this issue, we first create a new invoice. As first step, we can go to a subscription, select some of them and "create invoice items"

![image](https://user-images.githubusercontent.com/13901369/87019418-de97ba80-c1d2-11ea-8b93-bbaeff0e8793.png)

After this, go to the  finances section, click in the "invoice items". Select the invoice items that were created and click on "Create invoices"

![image](https://user-images.githubusercontent.com/13901369/87019730-3d5d3400-c1d3-11ea-995b-38517757c0fb.png)

select a title and create. As a feedback, we have 2 messages. The warning about the status "open" should not be visible at this stage. This is only valid before the creation. The condition to be added is the same that the one for the switch of the buttons, from "create" to "close"

![image](https://user-images.githubusercontent.com/13901369/87020174-ca07f200-c1d3-11ea-851c-619e9a2106f3.png)

The file where all that happens is in rechnungspositionen/overview/rechnungspositionenoverviewcreaterechnungen.html

**Comment by AlwinEgger** [comment]
Hidden after button is clicked
